import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve(new URL('..',import.meta.url).pathname),prod=path.join(root,'production');
const watcher=fs.readFileSync(path.join(prod,'LIGHT_PRODUCTION_WATCHER.js'),'utf8');
const bridge=fs.readFileSync(path.join(prod,'RelayCodexLightProduction.ps1'),'utf8');
const schema=JSON.parse(fs.readFileSync(path.join(prod,'LIGHT_PRODUCTION_ACTION.schema.json'),'utf8'));
const runner=fs.readFileSync(path.join(prod,'RUN_LIGHT_PRODUCTION_TARGET.ps1'),'utf8');
assert.equal(schema.additionalProperties,false);assert.deepEqual(schema.properties.action.enum,['SEND_PROMPT','STOP','HUMAN']);
for(const x of ['composer-submit-button-color','Start Voice','Send prompt','LIGHT_COPY_SENTINEL_','copy-back did not replace sentinel','normalizeEditorClipboard','\\u00A0+$','baseline_submit_aria','pasted_submit_aria','copy_sentinel_replaced','staged_copy_exact','bridge_prompt_sha256','SEND_AMBIGUOUS','SEND_AMBIGUOUS_NO_RETRY','LIGHT_MAX_SENDS = 1','${KEY_CTRL+KEY_V}','${KEY_CTRL+KEY_A}','${KEY_CTRL+KEY_C}'])assert.ok(watcher.includes(x),`watcher missing ${x}`);
assert.ok(!watcher.includes('firstEnabled('),'must not use the failed selector-only Send discovery helper');
assert.ok(!watcher.includes('all(l,timeout,true).filter(enabled)'),'must not click a match obtained only via includeHidden:true');
assert.equal((watcher.match(/uiv\.browser\.type/g)||[]).length,3);
assert.ok(watcher.includes("const COMPOSER = 'css=[role=\"textbox\"][contenteditable=\"true\"][aria-label=\"Chat with ChatGPT\"]';"),'watcher must use the Q08 target-qualified composer locator');
assert.equal((watcher.match(/uiv\.browser\.click\(COMPOSER\)/g)||[]).length,2,'paste and copy-back must focus via the Q08 locator string');
assert.ok(!watcher.includes('uiv.browser.click(composer)'),'must not focus composer through a finder snapshot');
assert.ok(!watcher.includes('uiv.browser.click(staged)'),'must not refocus composer through a finder snapshot');
assert.equal((watcher.match(/XRunAndWait/g)||[]).length,1);
assert.ok(!watcher.includes('uiv.browser.type(prompt)'));
for(const forbidden of ['uiv.page.','uiv.eval(','uiv.ocr.','uiv.ai.','uiv.shot.','uiv.desktop.','uiv.open(','XClick','XType','FRESH_CHAT'])assert.ok(!watcher.includes(forbidden),`watcher contains ${forbidden}`);
for(const x of ["'--ephemeral'","'--ignore-user-config'","'--sandbox'","'read-only'","'--output-schema'","'--output-last-message'",'Do not use tools','SEND_PROMPT','STOP','HUMAN'])assert.ok(bridge.includes(x),`bridge missing ${x}`);
for(const x of ['LIGHT_PRODUCTION_WATCHER.js','Reply exactly LIGHT_PRODUCTION_TARGET_OK.','LIGHT_PRODUCTION_evidence_','PASS','FAIL','[IO.Directory]::CreateDirectory($MacroDir)','Test-Path -LiteralPath $MacroDir -PathType Container'])assert.ok(runner.includes(x),`runner missing ${x}`);
assert.ok(!runner.includes('@($Chrome,$Launcher,$MacroDir,$WatcherSource,$BridgeSource,$SchemaSource)'),'macro staging directory must not be a hard pre-existing-path prerequisite');
console.log('LIGHT PRODUCTION CONTRACT TESTS: PASS');
