import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve(new URL('..',import.meta.url).pathname),prod=path.join(root,'production');
const harness=fs.readFileSync(path.join(prod,'RUN_LIGHT_MASTER_QUALIFICATION.ps1'),'utf8'),bridge=fs.readFileSync(path.join(prod,'RelayCodexLightProduction.ps1'),'utf8'),watcher=fs.readFileSync(path.join(prod,'LIGHT_PRODUCTION_WATCHER.js'),'utf8'),contract=fs.readFileSync(path.join(root,'MASTER_QUALIFICATION_CONTRACT.md'),'utf8');
for(const token of ["label='SEED'","label='SOAK_01'","label='SOAK_02'","label='SOAK_03'","label='SOAK_04'","label='SOAK_05'","label='TERMINAL_STOP'","expected_action='STOP'","expected_action='SEND_PROMPT'","material_send=$false","material_send=$true",'master_qualification_mode = $true','conversation continuity','user-message chain','assistant-message chain','source assistant sha256','nonce reused','Codex prompt sha256','baseline submit surface','primer submit surface','primer cleared surface','pasted submit surface','copy sentinel','staged copy','Send count','submission confirmation','next completion','STOP primer surface must be untouched','STOP primer clear surface must be untouched','MASTER_SUMMARY.csv','SHA256.txt','CYCLES_REQUIRED=7'])assert.ok(harness.includes(token),`master harness missing ${token}`);
assert.equal((harness.match(/\[pscustomobject\]@\{ index=/g)||[]).length,7);assert.equal((harness.match(/qualification_mode=\$false/g)||[]).length,6);assert.equal((harness.match(/material_send=\$true/g)||[]).length,6);assert.equal((harness.match(/material_send=\$false/g)||[]).length,1);assert.ok(!/uiv\.|browser\.click|browser\.type/.test(harness));
for(const token of ['$MasterQualificationMode = $false','master qualification conversation id mismatch','master qualification action mismatch','master qualification prompt sha256 mismatch'])assert.ok(bridge.includes(token));
for(const token of ['bridge_prompt_sha256','primer_submit_aria','primer_cleared_aria'])assert.ok(watcher.includes(token),`watcher missing ${token}`);
for(const token of ['Seven-cycle plan','production semantic soak','production terminal STOP','never automatically retried','fresh-chat/recovery remains the next separate stage'])assert.ok(contract.includes(token),`contract missing ${token}`);
console.log('LIGHT MASTER QUALIFICATION STATIC CONTRACT: PASS');
